# Generated by Django 3.1.3 on 2021-01-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0002_homepageform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageForm',
            new_name='HomePageFormModel',
        ),
    ]
