# Generated by Django 3.1.3 on 2021-01-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0003_auto_20210115_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageformmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
